services:
  - type: web
    name: metagram
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: metagram
      - key: MONGODB_KEEPALIVE_INTERVAL_MS
        value: 600000
      - key: SELF_PING_ENABLED
        value: true
      - key: SELF_PING_INTERVAL_MS
        value: 720000
      - key: JWT_SECRET
        generateValue: true
